### ISSUE TITLE
Working or not?

### ISSUE THREAD

**Issue by odera89** [no81no/jplist-github-wordpress-plugin#1]
This plugin is working or not? I want to test but not worked. Any suggestion?

And the demo page why not work?

**Comment by no81no** [comment]
The website was down for awhile, but it works now:
http://wordpress.jplist.com/

**Comment by musictomy** [comment]
The website mentioned does not Demo anything other that normal post, or am I missing something?

**Comment by no81no** [comment]
I'm sorry, it was wrong link. Please check here:
http://wordpress.jplist.com/jplist-for-posts-sorting-filtering-and-pagination/

**Comment by musictomy** [comment]
Thank you, So is it a case of just installing your plugin, looks great. Is your Plugin for wordpress on wordpress.org site?

**Comment by no81no** [comment]
It's not on wordpress.org, please download it from github
https://github.com/no81no/jplist-github-wordpress-plugin/archive/master.zip

**Comment by musictomy** [comment]
hi, Thanks

Have installed on localhost, but where to go from here no documentation for how to set filters on wordpress post and to show as you have done on your demo.

Cheers

**Comment by musictomy** [comment]
I get this within wordpress settings:

![capture](https://cloud.githubusercontent.com/assets/8762957/7724672/836f184c-feeb-11e4-8a76-91876ffb2b48.PNG)

**Comment by odera89** [comment]
Rename the plugin folder to "jplist"

**Comment by musictomy** [comment]
Ahha, thank you that's done the trick

**Comment by no81no** [comment]
jplist folder is created on github, so I close this issue.
